name: build

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

permissions:
  contents: read

jobs:
  dryrun-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://snakemake/snakemake:v7.32.4
      - name: Dry-run
        run: |
          docker run -v $PWD:/opt2 -w /opt2 snakemake/snakemake:v7.32.4 \
            ./bin/renee run \
              --input .tests/KO_S3.R1.fastq.gz .tests/KO_S3.R2.fastq.gz .tests/KO_S4.R1.fastq.gz .tests/KO_S4.R2.fastq.gz .tests/WT_S1.R1.fastq.gz .tests/WT_S1.R2.fastq.gz .tests/WT_S2.R1.fastq.gz .tests/WT_S2.R2.fastq.gz \
              --output output \
              --genome config/genomes/biowulf/hg38_30.json \
              --shared-resources .tests/shared_resources/ \
              --mode local \
              --dry-run
      - name: Lint
        continue-on-error: true
        run: |
          docker run -v $PWD:/opt2 snakemake/snakemake:v7.32.4 \
            snakemake --lint -s /opt2/output/workflow/Snakefile -d /opt2/output || \
          echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        snakemake-version: ["7.32.3"]
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test
          cache-environment: true
          condarc: |
            channels:
              - conda-forge
              - bioconda
          create-args: >-
            python=${{ matrix.python-version }}
            snakemake=${{ matrix.snakemake-version }}
            setuptools
            pip
            pytest
      - name: check CLI basics
        run: |
          ./bin/renee --help
          ./bin/renee --version
        shell: micromamba-shell {0}
      - name: pip install python package
        run: |
          pip install \
            --extra-index-url https://PySimpleGUI.net/install \
            .[dev,test]
        shell: micromamba-shell {0}
      - name: Test
        run: |
          python -m pytest --cov
        env:
          TMPDIR: ${{ runner.temp }}
        shell: micromamba-shell {0}
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build-status: # https://github.com/orgs/community/discussions/4324#discussioncomment-3477871
    runs-on: ubuntu-latest
    needs: [dryrun-lint, test]
    if: always()
    steps:
      - name: Successful build
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing build
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
